<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="37499" started-at="2019-06-16T21:10:03Z" finished-at="2019-06-16T21:10:41Z">
    <groups>
      <group name="regression">
        <method signature="LoginPageTest.wrongLogin()[pri:0, instance:com.syntax.testcases.LoginPageTest@67b6d4ae]" name="wrongLogin" class="com.syntax.testcases.LoginPageTest"/>
      </group> <!-- regression -->
      <group name="smoke">
        <method signature="LoginPageTest.doLogin()[pri:0, instance:com.syntax.testcases.LoginPageTest@67b6d4ae]" name="doLogin" class="com.syntax.testcases.LoginPageTest"/>
        <method signature="LoginPageTest.loginToOrangeHRM()[pri:0, instance:com.syntax.testcases.LoginPageTest@67b6d4ae]" name="loginToOrangeHRM" class="com.syntax.testcases.LoginPageTest"/>
      </group> <!-- smoke -->
    </groups>
    <test name="Test" duration-ms="37499" started-at="2019-06-16T21:10:03Z" finished-at="2019-06-16T21:10:41Z">
      <class name="com.syntax.testcases.LoginPageTest">
        <test-method status="PASS" signature="generateReport()[pri:0, instance:com.syntax.testcases.LoginPageTest@67b6d4ae]" name="generateReport" is-config="true" duration-ms="389" started-at="2019-06-16T21:10:03Z" finished-at="2019-06-16T21:10:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateReport -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.syntax.testcases.LoginPageTest@67b6d4ae]" name="setUp" is-config="true" duration-ms="7192" started-at="2019-06-16T21:10:03Z" finished-at="2019-06-16T21:10:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="doLogin()[pri:0, instance:com.syntax.testcases.LoginPageTest@67b6d4ae]" name="doLogin" duration-ms="4382" started-at="2019-06-16T21:10:11Z" finished-at="2019-06-16T21:10:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.syntax.testcases.LoginPageTest@67b6d4ae]" name="tearDown" is-config="true" duration-ms="791" started-at="2019-06-16T21:10:15Z" finished-at="2019-06-16T21:10:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.syntax.testcases.LoginPageTest@67b6d4ae]" name="setUp" is-config="true" duration-ms="5030" started-at="2019-06-16T21:10:16Z" finished-at="2019-06-16T21:10:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginToOrangeHRM()[pri:0, instance:com.syntax.testcases.LoginPageTest@67b6d4ae]" name="loginToOrangeHRM" duration-ms="10257" started-at="2019-06-16T21:10:21Z" finished-at="2019-06-16T21:10:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToOrangeHRM -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.syntax.testcases.LoginPageTest@67b6d4ae]" name="tearDown" is-config="true" duration-ms="852" started-at="2019-06-16T21:10:31Z" finished-at="2019-06-16T21:10:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.syntax.testcases.LoginPageTest@67b6d4ae]" name="setUp" is-config="true" duration-ms="4961" started-at="2019-06-16T21:10:32Z" finished-at="2019-06-16T21:10:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="wrongLogin()[pri:0, instance:com.syntax.testcases.LoginPageTest@67b6d4ae]" name="wrongLogin" duration-ms="2771" started-at="2019-06-16T21:10:37Z" finished-at="2019-06-16T21:10:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.syntax.testcases.LoginPageTest.wrongLogin(LoginPageTest.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wrongLogin -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.syntax.testcases.LoginPageTest@67b6d4ae]" name="tearDown" is-config="true" duration-ms="806" started-at="2019-06-16T21:10:40Z" finished-at="2019-06-16T21:10:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="flushReport()[pri:0, instance:com.syntax.testcases.LoginPageTest@67b6d4ae]" name="flushReport" is-config="true" duration-ms="5" started-at="2019-06-16T21:10:41Z" finished-at="2019-06-16T21:10:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReport -->
      </class> <!-- com.syntax.testcases.LoginPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
